language: node_js
node_js:
  - "8"
cache: npm
before_install:
  - npm i -g npm
install:
  - npm ci
jobs:
  include:
    - stage: test
      script: npm run test

    # - stage: build
    #   script: npm run build
    #   env:
    #     - NODE_ENV=production
